### ISSUE TITLE
Check dm02

### ISSUE THREAD

**Issue by wongkerry** [jarvisc1/comix_data_clean#10]
Confirm that dm02 works on computer and gives expected output.

**Comment by wongkerry** [comment]
Checked and did not find any issues. @jarvisc1 if haven't yet, I suggest we test that the code can handle empty and multiple country/panel/wave as expected, but it's low priority.

**Comment by jarvisc1** [comment]
Cool currently it filters if the SPSS file is missing. Probably should add some checks in to say wave or panel or country is missing. 

or do you mean for the function? If so then I can add some code for that as have already written it.

**Comment by jarvisc1** [comment]
@wongkerry  Could you can recheck this file. I've added the change to ID variable here as it's an important variable like the country, panel, and wave. I'm changing it from running 1-10000 to each panel starting from 10,000. Might need to take a look at this and determine whether the new data will come in a different format and do different number for each country. 

the second bit is more involved and perhaps should be moved out to be a function. The parent questions use different variables names such as qp54 instead of q54. We have to identify the children, change the names of the columns and then combine it back with the adult data.

**Comment by jarvisc1** [comment]
Reviewed by @wongkerry
