### ISSUE TITLE
check diagnostic testing questions

### ISSUE THREAD

**Issue by amygimma** [jarvisc1/comix_data_clean#27]
Should there be 4 distinct test questions (see questions below)? 
	- antibody test anytime (panels E & F)
	- nose/throat within 14 days (panels E & F)
	-  nose/throat prior to 14 days ago (panels E & F)
        - any covid test (Panels A - D)

Questions:

Panel A - D
Q32. Have you, or any other household member, ever been tested for Coronavirus (Covid-19)? (answer: y/n)
Q33. Who has been tested for Coronavirus (Covid-19)? (answer: household member results)
Q34. To the best of your knowledge, do you think you or anyone else in your household have been in direct contact with someone who has Coronavirus (Covid-19) in the last seven days, or know someone close to them who has Coronavirus (Covid-19)?

Panels E & F
IF SAMPLETYPE = 1 Q32. Have you been tested for Coronavirus (Covid-19) via a nose and/or throat swab in the last fourteen days? IF SAMPLETYPE = 2 Q32. Has NAME been tested for Coronavirus (Covid-19) via a nose and/or throat swab in the last fourteen days? (answer: adult/child results)
Q32a. Have you been tested for Coronavirus (Covid-19) via a nose and/or throat swab prior to the past fourteen days? ASK IF WAVE=1 AND IF SAMPLETYPE = 2 Q32a Has [NAME] been tested for Coronavirus (Covid-19) via a nose and/or throat swab prior to the past fourteen days? (answer: adult/child results)
Q32b. Have you ever been tested for Coronavirus (Covid-19) via a blood test (antibodies test)? IF SAMPLETYPE = 2 Q32b. Has [NAME] ever been tested for for Coronavirus (Covid-19) via a blood test (antibodies test)? (answer: adult/child results)

**Comment by wongkerry** [comment]
Agreed that there are 4 distinct test questions:

**Panel A - D**
Q32. Have you, or any other household member, ever been tested for Coronavirus (Covid-19)? (answer: y/n)

- q32 is renamed to hhm_covid_test, no action required (4th in Amy's list above)

**Panels E & F**
IF SAMPLETYPE = 1 Q32. Have you been tested for Coronavirus (Covid-19) via a nose and/or throat swab in the last fourteen days? IF SAMPLETYPE = 2 Q32. Has NAME been tested for Coronavirus (Covid-19) via a nose and/or throat swab in the last fourteen days? (answer: adult/child results)

- **Action**: in var_name.xlsx file, survey_2 tab: rename q32 to `part_covid_test_recent` instead of `hhm_covid_test_recent` (2nd in Amy's list)

Q32a. Have you been tested for Coronavirus (Covid-19) via a nose and/or throat swab prior to the past fourteen days? ASK IF WAVE=1 AND IF SAMPLETYPE = 2 Q32a Has [NAME] been tested for Coronavirus (Covid-19) via a nose and/or throat swab prior to the past fourteen days? (answer: adult/child results)

- q32a is renamed to part_covid_test_past, no action required (3rd in Amy's list)

Q32b. Have you ever been tested for Coronavirus (Covid-19) via a blood test (antibodies test)? IF SAMPLETYPE = 2 Q32b. Has [NAME] ever been tested for for Coronavirus (Covid-19) via a blood test (antibodies test)? (answer: adult/child results)

- q32b is renamed to part_antibody_test, no action required (1st in Amy's list)
