### ISSUE TITLE
Check dm01

### ISSUE THREAD

**Issue by jarvisc1** [jarvisc1/comix_data_clean#8]
Confirm that dm01 works on computer and gives expected output.

**Comment by wongkerry** [comment]
1. **_First time_** I ran dm01, it failed to find spss files from "Filr\Net Folders\EPH Shared\Comix_survey\data\spss". 

(proposed) solution: issue went away **_after_** I manually accessed the folder from File Explorer. might need to add this to the instructions?

**Comment by wongkerry** [comment]
2. Complained I do not have the qs package... 

(proposed) solution: I can see that there is 00_install_packages.R in the repo, but seems like it' not currently included as part of the process. Add it in?

**Comment by wongkerry** [comment]
3. (same for occurrences in the other dm files) May need new codes to read all country names from data/spss_files.xlsx such that this process can be run for all EpiPose countries?

Propose 
`country_codes <- readxl::excel_sheets('data/spss_files.xlsx')`
`country_codes <- country_codes[-1]`

instead of 
`country_codes <- c("UK", "NL", "BE", "NO")`

**Comment by jarvisc1** [comment]
Very helpful. These won't affect the cleaning so I suggest we revisit them once the whole cleaning is done. 
Initial thoughts. 

1. Yeah could be added to readme

2. Yeah if so then make it so it checks the packages

3.  Yeah could do but it will also be handy to have the list in case we want to just run a single country manually in future.
